from database import SessionLocal, init_db
from models import Food

SAMPLE_FOODS = [
    {
        "name": "白米饭",
        "brand": None,
        "category": "主食",
        "barcode": "6901234567890",
        "calories": 116,
        "protein": 2.6,
        "fat": 0.3,
        "carbs": 25.9,
        "fiber": 0.3,
        "sugar": 0,
        "sodium": 2,
        "health_score": 60,
        "nova_class": 1,
        "ingredients": ["大米", "水"],
        "allergens": [],
        "serving_size": 100,
        "serving_unit": "g"
    },
    {
        "name": "全麦面包",
        "brand": "桃李",
        "category": "主食",
        "barcode": "6901234567891",
        "calories": 246,
        "protein": 9.5,
        "fat": 3.2,
        "carbs": 46.4,
        "fiber": 6.0,
        "sugar": 4.5,
        "sodium": 450,
        "health_score": 75,
        "nova_class": 2,
        "ingredients": ["全麦面粉", "水", "酵母", "盐"],
        "allergens": ["麸质"],
        "serving_size": 100,
        "serving_unit": "g"
    },
    {
        "name": "鸡胸肉",
        "brand": None,
        "category": "肉类",
        "barcode": "6901234567892",
        "calories": 133,
        "protein": 19.4,
        "fat": 5.0,
        "carbs": 2.5,
        "fiber": 0,
        "sugar": 0,
        "sodium": 63,
        "health_score": 90,
        "nova_class": 1,
        "ingredients": ["鸡胸肉"],
        "allergens": [],
        "serving_size": 100,
        "serving_unit": "g"
    },
    {
        "name": "三文鱼",
        "brand": None,
        "category": "海鲜",
        "barcode": "6901234567893",
        "calories": 208,
        "protein": 20.4,
        "fat": 13.4,
        "carbs": 0,
        "fiber": 0,
        "sugar": 0,
        "sodium": 59,
        "health_score": 95,
        "nova_class": 1,
        "ingredients": ["三文鱼"],
        "allergens": ["鱼类"],
        "serving_size": 100,
        "serving_unit": "g"
    },
    {
        "name": "西兰花",
        "brand": None,
        "category": "蔬菜",
        "barcode": "6901234567894",
        "calories": 34,
        "protein": 2.8,
        "fat": 0.4,
        "carbs": 6.6,
        "fiber": 2.6,
        "sugar": 1.7,
        "sodium": 33,
        "health_score": 98,
        "nova_class": 1,
        "ingredients": ["西兰花"],
        "allergens": [],
        "serving_size": 100,
        "serving_unit": "g"
    },
    {
        "name": "牛奶",
        "brand": "伊利",
        "category": "乳制品",
        "barcode": "6901234567895",
        "calories": 54,
        "protein": 3.0,
        "fat": 3.2,
        "carbs": 4.8,
        "fiber": 0,
        "sugar": 4.8,
        "sodium": 42,
        "health_score": 80,
        "nova_class": 1,
        "ingredients": ["生牛乳"],
        "allergens": ["乳制品"],
        "serving_size": 100,
        "serving_unit": "ml"
    },
    {
        "name": "苹果",
        "brand": None,
        "category": "水果",
        "barcode": "6901234567896",
        "calories": 52,
        "protein": 0.3,
        "fat": 0.2,
        "carbs": 13.8,
        "fiber": 2.4,
        "sugar": 10.4,
        "sodium": 1,
        "health_score": 92,
        "nova_class": 1,
        "ingredients": ["苹果"],
        "allergens": [],
        "serving_size": 100,
        "serving_unit": "g"
    },
    {
        "name": "鸡蛋",
        "brand": None,
        "category": "蛋类",
        "barcode": "6901234567897",
        "calories": 144,
        "protein": 13.3,
        "fat": 8.8,
        "carbs": 2.8,
        "fiber": 0,
        "sugar": 2.8,
        "sodium": 140,
        "health_score": 88,
        "nova_class": 1,
        "ingredients": ["鸡蛋"],
        "allergens": ["鸡蛋"],
        "serving_size": 100,
        "serving_unit": "g"
    },
    {
        "name": "燕麦片",
        "brand": "桂格",
        "category": "主食",
        "barcode": "6901234567898",
        "calories": 367,
        "protein": 14.7,
        "fat": 6.9,
        "carbs": 61.8,
        "fiber": 10.3,
        "sugar": 1.4,
        "sodium": 4,
        "health_score": 85,
        "nova_class": 1,
        "ingredients": ["燕麦"],
        "allergens": ["麸质"],
        "serving_size": 100,
        "serving_unit": "g"
    },
    {
        "name": "豆腐",
        "brand": None,
        "category": "豆制品",
        "barcode": "6901234567899",
        "calories": 76,
        "protein": 8.1,
        "fat": 4.2,
        "carbs": 1.9,
        "fiber": 0.4,
        "sugar": 0.5,
        "sodium": 7,
        "health_score": 90,
        "nova_class": 1,
        "ingredients": ["大豆", "水", "凝固剂"],
        "allergens": ["大豆"],
        "serving_size": 100,
        "serving_unit": "g"
    },
    {
        "name": "薯片(原味)",
        "brand": "乐事",
        "category": "零食",
        "barcode": "6901234567900",
        "calories": 536,
        "protein": 6.0,
        "fat": 35.0,
        "carbs": 50.0,
        "fiber": 4.4,
        "sugar": 0.5,
        "sodium": 525,
        "health_score": 25,
        "nova_class": 4,
        "ingredients": ["马铃薯", "植物油", "盐"],
        "allergens": [],
        "serving_size": 100,
        "serving_unit": "g"
    },
    {
        "name": "可乐",
        "brand": "可口可乐",
        "category": "饮料",
        "barcode": "6901234567901",
        "calories": 42,
        "protein": 0,
        "fat": 0,
        "carbs": 10.6,
        "fiber": 0,
        "sugar": 10.6,
        "sodium": 4,
        "health_score": 15,
        "nova_class": 4,
        "ingredients": ["碳酸水", "糖", "焦糖色", "磷酸", "咖啡因"],
        "allergens": [],
        "serving_size": 100,
        "serving_unit": "ml"
    },
    {
        "name": "牛肉",
        "brand": None,
        "category": "肉类",
        "barcode": "6901234567902",
        "calories": 250,
        "protein": 26.0,
        "fat": 15.0,
        "carbs": 0,
        "fiber": 0,
        "sugar": 0,
        "sodium": 72,
        "health_score": 82,
        "nova_class": 1,
        "ingredients": ["牛肉"],
        "allergens": [],
        "serving_size": 100,
        "serving_unit": "g"
    },
    {
        "name": "酸奶(原味)",
        "brand": "安慕希",
        "category": "乳制品",
        "barcode": "6901234567903",
        "calories": 97,
        "protein": 3.1,
        "fat": 3.0,
        "carbs": 12.0,
        "fiber": 0,
        "sugar": 10.0,
        "sodium": 65,
        "health_score": 70,
        "nova_class": 3,
        "ingredients": ["生牛乳", "白砂糖", "乳酸菌"],
        "allergens": ["乳制品"],
        "serving_size": 100,
        "serving_unit": "g"
    },
    {
        "name": "香蕉",
        "brand": None,
        "category": "水果",
        "barcode": "6901234567904",
        "calories": 89,
        "protein": 1.1,
        "fat": 0.3,
        "carbs": 22.8,
        "fiber": 2.6,
        "sugar": 12.2,
        "sodium": 1,
        "health_score": 88,
        "nova_class": 1,
        "ingredients": ["香蕉"],
        "allergens": [],
        "serving_size": 100,
        "serving_unit": "g"
    },
    {
        "name": "黄瓜",
        "brand": None,
        "category": "蔬菜",
        "barcode": "6901234567905",
        "calories": 15,
        "protein": 0.7,
        "fat": 0.1,
        "carbs": 3.6,
        "fiber": 0.5,
        "sugar": 1.7,
        "sodium": 2,
        "health_score": 96,
        "nova_class": 1,
        "ingredients": ["黄瓜"],
        "allergens": [],
        "serving_size": 100,
        "serving_unit": "g"
    },
    {
        "name": "猪肉(瘦)",
        "brand": None,
        "category": "肉类",
        "barcode": "6901234567906",
        "calories": 143,
        "protein": 20.3,
        "fat": 6.2,
        "carbs": 0,
        "fiber": 0,
        "sugar": 0,
        "sodium": 65,
        "health_score": 78,
        "nova_class": 1,
        "ingredients": ["猪肉"],
        "allergens": [],
        "serving_size": 100,
        "serving_unit": "g"
    },
    {
        "name": "番茄",
        "brand": None,
        "category": "蔬菜",
        "barcode": "6901234567907",
        "calories": 18,
        "protein": 0.9,
        "fat": 0.2,
        "carbs": 3.9,
        "fiber": 1.2,
        "sugar": 2.6,
        "sodium": 5,
        "health_score": 95,
        "nova_class": 1,
        "ingredients": ["番茄"],
        "allergens": [],
        "serving_size": 100,
        "serving_unit": "g"
    },
    {
        "name": "方便面",
        "brand": "康师傅",
        "category": "主食",
        "barcode": "6901234567908",
        "calories": 472,
        "protein": 9.5,
        "fat": 21.1,
        "carbs": 61.6,
        "fiber": 1.2,
        "sugar": 1.8,
        "sodium": 2300,
        "health_score": 20,
        "nova_class": 4,
        "ingredients": ["小麦粉", "植物油", "盐", "调味料"],
        "allergens": ["麸质"],
        "serving_size": 100,
        "serving_unit": "g"
    },
    {
        "name": "坚果混合",
        "brand": "三只松鼠",
        "category": "零食",
        "barcode": "6901234567909",
        "calories": 590,
        "protein": 18.0,
        "fat": 50.0,
        "carbs": 20.0,
        "fiber": 8.0,
        "sugar": 5.0,
        "sodium": 10,
        "health_score": 72,
        "nova_class": 1,
        "ingredients": ["杏仁", "腰果", "核桃", "榛子"],
        "allergens": ["坚果"],
        "serving_size": 100,
        "serving_unit": "g"
    }
]

def init_sample_data():
    db = SessionLocal()
    try:
        existing_count = db.query(Food).count()
        if existing_count > 0:
            print(f"数据库已有 {existing_count} 条食物数据，跳过初始化")
            return
        
        for food_data in SAMPLE_FOODS:
            food = Food(**food_data)
            db.add(food)
        
        db.commit()
        print(f"成功初始化 {len(SAMPLE_FOODS)} 条示例食物数据")
    except Exception as e:
        print(f"初始化数据失败: {e}")
        db.rollback()
    finally:
        db.close()

if __name__ == "__main__":
    print("初始化数据库...")
    init_db()
    print("初始化示例数据...")
    init_sample_data()
    print("完成!")
